### ISSUE TITLE
Missing part due to the switch to the main Robotis Library

### ISSUE THREAD

**Issue by matthieu-lapeyre** [Alexandre-lefalher/creature#2]
Hi Alexandre,

As I replaced the copy of the robotis_library by the link to the Robotis library repository, it seems the following parts are missing:
- BPF-WA.SLDPRT
- BPF-BU.SLDPRT

These elements should be added to the Robotis Library, I could do it but it would be better to let you do it so you keep authorship of the contribution.

Can you fork the [Robotis Library](https://github.com/poppy-project/Robotis-library) and add the missing part ?

Of course, if you do not have the time to do it, I can do it for you.

**Comment by PirouetteNeroz** [comment]
Hi Matthieu,

It is possible to push the missing parts beacause I have some error

"git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --tags origin master:master
remote: Permission to poppy-project/Robotis-library.git denied to alexandre-lefalher.
fatal: unable to access 'https://github.com/poppy-project/Robotis-library.git/': The requested URL returned error: 403

Pushing to https://github.com/poppy-project/Robotis-library.git"
